name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
